export const CHANGE_STATIC_GRADE = "home/CHANGE_STATIC_GRADE";
export const CHINA_DAY_LIST = "home/CHINA_DAY_LIST";
export const CHINA_ADD_DAY_LIST = "home/CHINA_ADD_DAY_LIST";
export const CHINS_PROVIENCE_DATA = "hone/CHINS_PROVIENCE_DATA";
