export const CHANGE_STATIC_GRADE = "home/CHANGE_STATIC_GRADE";
export const CHANGE_TOP_BANNERS = "home/CHANGE_TOP_BANNERS";
export const CHANGE_HOME_GOODLIST = "home/CHANGE_HOME_GOODLIST";
export const CHANGE_HOME_GOODLIST_TYPE = "home/CHANGE_HOME_GOODLIST_TYPE";
